### ISSUE TITLE
Installation failure

### ISSUE THREAD

**Issue by RossBoylan** [ecfairle/mccli#2]
Hi.  I'm working with your Mom on this project.  I'm trying to install the code on linux, but am not getting very far.
```
ross@ross-node1:~/KBD$ date; npm install  @ecfairle/mccli
Fri Nov 30 14:02:08 PST 2018
npm ERR! addLocal Could not install ecfairle/mccli
npm ERR! Error: ENOENT, stat 'ecfairle/mccli'
npm ERR! If you need help, you may report this *entire* log,
npm ERR! including the npm and node versions, at:
npm ERR!     <http://github.com/npm/npm/issues>

npm ERR! System Linux 3.16.0-7-amd64
npm ERR! command "/usr/bin/nodejs" "/usr/bin/npm" "install" "@ecfairle/mccli"
npm ERR! cwd /home/ross/KBD
npm ERR! node -v v0.10.29
npm ERR! npm -v 1.4.21
npm ERR! path ecfairle/mccli
npm ERR! code ENOENT
npm ERR! errno 34
npm ERR! 
npm ERR! Additional logging details can be found in:
npm ERR!     /home/ross/KBD/npm-debug.log
npm ERR! not ok code 0
```
I've attached the full  [npm-debug.log](https://github.com/ecfairle/mccli/files/2635176/npm-debug.log)  from the previous try.

I also tried it exactly as written in the instructions, with -g,
```
ross@ross-node1:~/KBD$ date; npm install -g @ecfairle/mccli
Fri Nov 30 13:59:27 PST 2018
npm ERR! addLocal Could not install ecfairle/mccli
npm ERR! Error: ENOENT, stat 'ecfairle/mccli'
npm ERR! If you need help, you may report this *entire* log,
npm ERR! including the npm and node versions, at:
npm ERR!     <http://github.com/npm/npm/issues>

npm ERR! System Linux 3.16.0-7-amd64
npm ERR! command "/usr/bin/nodejs" "/usr/bin/npm" "install" "-g" "@ecfairle/mccli"
npm ERR! cwd /home/ross/KBD
npm ERR! node -v v0.10.29
npm ERR! npm -v 1.4.21
npm ERR! path ecfairle/mccli
npm ERR! code ENOENT
npm ERR! errno 34
npm ERR! 
npm ERR! Additional logging details can be found in:
npm ERR!     /home/ross/KBD/npm-debug.log
npm ERR! not ok code 0
```
I had hoped the ENOENT was a local permission issue, since I did not anticipate the -g option would be successful.

That was all from sessions in which I had an ssh agent running.  Without it results were worse.  I also tried installing it directly from my local disk.  No joy.
```
ross@ross-node1:~/KBDnpm install -g mccli/
npm ERR! addLocal Could not install mccli/
npm ERR! Error: Invalid name: "@ecfairle/mccli"
npm ERR!     at ensureValidName (/usr/lib/nodejs/normalize-package-data/lib/fixer.js:284:15)
npm ERR!     at Object.module.exports.fixNameField (/usr/lib/nodejs/normalize-package-data/lib/fixer.js:199:5)
npm ERR!     at /usr/lib/nodejs/normalize-package-data/lib/normalize.js:29:38
npm ERR!     at Array.forEach (native)
npm ERR!     at normalize (/usr/lib/nodejs/normalize-package-data/lib/normalize.js:28:15)
npm ERR!     at final (/usr/lib/nodejs/read-package-json/read-json.js:342:33)
npm ERR!     at then (/usr/lib/nodejs/read-package-json/read-json.js:126:33)
npm ERR!     at /usr/lib/nodejs/read-package-json/read-json.js:266:40
npm ERR!     at evalmachine.<anonymous>:272:14
npm ERR!     at /usr/lib/nodejs/graceful-fs/graceful-fs.js:102:5
npm ERR! If you need help, you may report this *entire* log,
npm ERR! including the npm and node versions, at:
npm ERR!     <http://github.com/npm/npm/issues>

npm ERR! System Linux 3.16.0-7-amd64
npm ERR! command "/usr/bin/nodejs" "/usr/bin/npm" "install" "-g" "mccli/"
npm ERR! cwd /home/ross/KBD
npm ERR! node -v v0.10.29
npm ERR! npm -v 1.4.21
npm ERR!
npm ERR! Additional logging details can be found in:
npm ERR!     /home/ross/KBD/npm-debug.log
npm ERR! not ok code 0

### next try
ross@ross-node1:~/KBD$ npm install -g @ecfairle/mccli
-^[[0G\^[[0G|^[[0G/^[[0G-^[[0G\^[[0G|^[[0G/^[[0G-^[[0G\^[[0G|^[[0G/^[[0Gnpm ERR! git clone git@github.com:ecfairle/mccli Cloning into bare repository '/home/ross/.npm/_g\
it-remotes/git-github-com-ecfairle-mccli-926c5886'...
npm ERR! git clone git@github.com:ecfairle/mccli Permission denied (publickey).
npm ERR! git clone git@github.com:ecfairle/mccli fatal: Could not read from remote repository.
npm ERR! git clone git@github.com:ecfairle/mccli
npm ERR! git clone git@github.com:ecfairle/mccli Please make sure you have the correct access rights
npm ERR! git clone git@github.com:ecfairle/mccli and the repository exists.
npm ERR! addLocal Could not install ecfairle/mccli
npm ERR! Error: ENOENT, stat 'ecfairle/mccli'
npm ERR! If you need help, you may report this *entire* log,
npm ERR! including the npm and node versions, at:
npm ERR!     <http://github.com/npm/npm/issues>

npm ERR! System Linux 3.16.0-7-amd64
npm ERR! command "/usr/bin/nodejs" "/usr/bin/npm" "install" "-g" "@ecfairle/mccli"
npm ERR! cwd /home/ross/KBD
npm ERR! node -v v0.10.29
npm ERR! npm -v 1.4.21
npm ERR! path ecfairle/mccli
npm ERR! code ENOENT
npm ERR! errno 34
npm ERR!
npm ERR! Additional logging details can be found in:
npm ERR!     /home/ross/KBD/npm-debug.log
npm ERR! not ok code 0

```

This was on Debian GNU/Linux 8 (oldstable) in which I preinstalled node.js, npm, python3, and a bunch of the dependencies listed in package.json via the Debian package manager.  For reasons that are unclear to me, some very basic modules, like fs, are not listed as available or described as being part of the basic node.js package.  Since ENOENT is nominally a filesystem error, I suppose lack of fs (if it's really not there) could be related.

I realize that at then end of this the Fortran code may not be runnable, but I'm just trying to understand the overall architecture of your code, as well as seeing how the installation attempt goes.

**Comment by RossBoylan** [comment]
The full debug log attached to the original report show a fetch via `git://` on line 11, which seems to work since later lines list the component files.  But then line 63 reports a fetch via `git+ssh://`, which also has later lines listing components.  Perhaps it is trying to stick both results in the same place and complaining because of that?

It's true that `ecfairle/mccli` is not in my directory tree before or after the install, but I don't think there should be any obstacle to creating it (except if it was already created by the first phase install starting at line 11).

**Comment by RossBoylan** [comment]
The full debug log attached to the original report show a fetch via `git://` on line 11, which seems to work since later lines list the component files.  But then line 63 reports a fetch via `git+ssh://`, which also has later lines listing components.  Perhaps it is trying to stick both results in the same place and complaining because of that?

It's true that `ecfairle/mccli` is not in my directory tree before or after the install, but I don't think there should be any obstacle to creating it (except if it was already created by the first phase install starting at line 11).

**Comment by RossBoylan** [comment]
Also, notice Node.js is v0.10.29. not 10.xx.yy, i.e., very old rather than current LTS.
Since Node.js and npm were packaged together, they probably should work together, but they may not support the current behavior of the npm website.

**Comment by ecfairle** [comment]
Hey Ross,

I didn't do any testing with linux and I also dont really have any other
experience with npm/node so I'm not sure what type of issues could be going
on. Which linux OS are you using?

**Comment by ecfairle** [comment]
Never mind I see the OS now in the original message. I'll look into it this
weekend and get back to you Monday

**Comment by RossBoylan** [comment]
Not directly related to the bug, but why is some of the functionality in javascript and some in python?

________________________________________

**Comment by ecfairle** [comment]
I made a virtual machine with debian 8 and wasn't able to reproduce the error you got. I did run into some other errors because of the hacky way the package is set up to interact with python, though. And yea -- the reason some is in python and some is in javascript is because I wrote the initial functionality in python and then wanted to have a CLI for the project that was easy to install and interact with and NPM was the best I could think of. But looking back I could've just made a pip package. 

Anyway, we can work together to get the current package running on your machine but I would say definitely make sure you can run the model first before worrying about if we can get this project running on linux.
